import About from "@/components/About";
import Intro from "@/components/Intro";
import Services from "@/components/Services";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Intro />
				<About />
				<Services />
			</main>
		</>
	);
}
