import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="text-5xl">Hello World</h1>
				<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam totam maiores, alias corrupti recusandae quae veritatis pariatur corporis sequi repudiandae debitis voluptatibus, sapiente, dolorem reprehenderit nesciunt! Cum, et vel? Quo quidem esse voluptates consectetur omnis repellendus quis officia numquam autem atque, quaerat minus architecto doloribus corporis magnam harum iste nisi.</p>
			</main>
		</>
	);
}
